// SPDX-License-Identifier: Apache-2.0
// editor/src/gui/font-metrics.ts
//
// The GUI font set as the editor sees it (docs/working-notes/gui-font-pipeline-scoping.md). The JSON files
// beside this are generated by tools/build_fonts.py from the same font_to_py run as the board modules
// (device-runtime/src/vendor/fonts/font_<id>.py), and device-runtime/test/test_fonts.py checks the two match
// glyph for glyph. So a width measured here is the width the board's Writer draws: fixed-height glyphs, no
// kerning, a string is the sum of its glyphs' widths. A character outside a font's charset is drawn as the
// font's error glyph ("?"), as on the board; missingChars() lets the layout engine refuse it instead.

export interface FontData {
  readonly id: string;
  readonly charset: "body" | "digits";
  /** Nominal size, the number in the id. Not the drawn height: font_to_py lands within a pixel of it. */
  readonly size: number;
  /** Line height in pixels, as Writer advances: what layout uses. */
  readonly height: number;
  readonly baseline: number;
  readonly maxWidth: number;
  readonly errchar: string;
  /** char -> [width, base64 bitmap]. Rows top to bottom, each (width + 7) >> 3 bytes, MSB = leftmost. */
  readonly glyphs: Readonly<Record<string, readonly [number, string]>>;
  readonly samples: Readonly<Record<string, number>>;
}

const modules = import.meta.glob<FontData>("./fonts/*.json", { eager: true, import: "default" });

const FONTS: ReadonlyMap<string, FontData> = new Map(Object.values(modules).map((f) => [f.id, f]));

/** Every font id in the set, sorted ("font_body12", ..., "font_digits64"). */
export function fontIds(): string[] {
  return [...FONTS.keys()].sort();
}

/** The font, or a thrown Error naming the unknown id. */
export function getFont(id: string): FontData {
  const f = FONTS.get(id);
  if (!f) throw new Error(`unknown font "${id}" (known: ${fontIds().join(", ")})`);
  return f;
}

function glyph(font: FontData, ch: string): readonly [number, string] {
  return font.glyphs[ch] ?? font.glyphs[font.errchar]!;
}

/** Width in pixels of `text` drawn in font `id`, exactly as the board's Writer draws it. */
export function textWidth(id: string, text: string): number {
  const font = getFont(id);
  let w = 0;
  for (const ch of text) w += glyph(font, ch)[0];
  return w;
}

/** Characters in `text` the font doesn't have (each once, in order of first use). */
export function missingChars(id: string, text: string): string[] {
  const font = getFont(id);
  const out: string[] = [];
  for (const ch of text) if (!(ch in font.glyphs) && !out.includes(ch)) out.push(ch);
  return out;
}

/** Width of the widest string of `maxChars` characters drawn from `chars` (default: the whole charset).
 * For a bound value whose text isn't known until runtime: its rect must fit the widest it can be. */
export function widestWidth(id: string, maxChars: number, chars?: string): number {
  const font = getFont(id);
  let widest = 0;
  for (const ch of chars ?? Object.keys(font.glyphs)) widest = Math.max(widest, glyph(font, ch)[0]);
  return widest * maxChars;
}

/** One glyph's pixels, for the GUI preview: `rows[y]` has bit (7 - x % 8) of byte x >> 3 set when pixel
 * x of row y is drawn. */
export function glyphBitmap(id: string, ch: string): { width: number; height: number; rows: Uint8Array[] } {
  const font = getFont(id);
  const [width, b64] = glyph(font, ch);
  const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const stride = (width + 7) >> 3;
  const rows: Uint8Array[] = [];
  for (let y = 0; y < font.height; y++) rows.push(bytes.subarray(y * stride, (y + 1) * stride));
  return { width, height: font.height, rows };
}
